# Generated by Django 3.1.7 on 2021-03-06 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PerroquetApp', '0005_auto_20210306_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birth_date',
            new_name='birthDate',
        ),
    ]
