# Generated by Django 3.1.7 on 2021-03-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PerroquetApp', '0012_auto_20210322_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
    ]
