# Generated by Django 3.1.7 on 2021-03-26 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PerroquetApp', '0013_auto_20210322_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='date_follow',
        ),
        migrations.AddField(
            model_name='follow',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='like',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
