# Generated by Django 3.1.7 on 2021-03-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PerroquetApp', '0014_auto_20210326_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='like',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
