# Generated by Django 3.1.7 on 2021-04-02 12:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PerroquetApp', '0017_auto_20210329_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='follower',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='author',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('user', 'following')},
        ),
    ]
